### ISSUE TITLE
problem with rawzfitsreader after updating digicampipe

### ISSUE THREAD

**Issue by AndriiNagai** [cta-sst-1m/protozfitsreader#27]
Dear All,

I tried to update digicampipe by following the instruction from: https://github.com/cta-sst-1m/digicampipe

But now I have a problem with rawzfitsreader, please see bellow
Do you have any suggestions or advises?
Thank you very much in advance.

P.S. I am using MacOS.

Bets regards,
Andrii

(digicampipe) Andriis-MacBook-Air-2:digicampipe nagai$ python digicampipe/scripts/digicamview.py ~/Documents/work/data/CTA_data/09_04_2018/SST1M_01_ZFITSWRITER001_000.004.fits.fz 
Traceback (most recent call last):
  File "digicampipe/scripts/digicamview.py", line 7, in <module>
    from digicampipe.io import event_stream
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/event_stream.py", line 1, in <module>
    from digicampipe.io import zfits, hdf5
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/zfits.py", line 11, in <module>
    import digicampipe.io.protozfitsreader as protozfitsreader
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/protozfitsreader.py", line 6, in <module>
    import rawzfitsreader
ImportError: No module named 'rawzfitsreader'
(digicampipe) Andriis-MacBook-Air-2:digicampipe nagai$

**Comment by dneise** [comment]
Hello Andrii, thanks for reporting!

First source of error is always: not having activated the conda environment... maybe you want to check that.

---

If that does not help...

One part of the installation procedure of digicampipe is this:

    pip install -r digicampipe/requirements.txt

One of the entries of this requirements.txt file is this:

    pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v0.44.1b0.tar.gz

Could you execute this command manually and paste the result here?

**Comment by calispac** [comment]
We looked into together I could not help. But I think it is somehow a similar issue to this : 
https://github.com/cta-sst-1m/digicampipe/issues/52

**Comment by dneise** [comment]
Ah wait. Sorry I did not pay attention. You said you *updated*, i.e. digicampipe including the protozfits reader did work before on your machine.... that is interesting.

Do you remember how old the version was, which did work? Maybe this gives us a handle

**Comment by AndriiNagai** [comment]
Thank you for suggestions.
I installed it on middle of October 2017...

**Comment by dneise** [comment]
Ah ... okay so I had a look at [digicampipe in 16. Oct. 2017](https://github.com/cta-sst-1m/digicampipe/tree/1dfd5a913a88b5f0da5cbec73c96589abefa53ec)

At this point in time the protozfitsreader package was still very different.

I would like to ask you to read this part of the README of the protozfitsreader again:
<https://github.com/cta-sst-1m/protozfitsreader/tree/v0.44.1b0#osx-with-anaconda>

And then please try again to install the protozfits reader. just there is an error in that README:
It should be:

    pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v0.44.1b0.tar.gz

not `v0.44.0.tar.gz`.

The rest of the installation procedure should be correct.... I do not have a Mac .. but I think somebody tried it and it worked ... it works a t least on travis.

In order to find out if the installation worked you can either do go to the protozfits folder and type `pytest` inside. Or you can start your python or ipython session and do:

    import protozfitsreader

**Comment by dneise** [comment]
Btw. I am sorry that the installation process on MacOS is far from easy ... any help is much appreciated.

**Comment by AndriiNagai** [comment]
No problem. Thank you for help. I will try your suggestions after lunch and let you know the results.

Best regards,
Andrii

**Comment by AndriiNagai** [comment]
Unfortunately, reinstallation of protozfits did not help(

(digicampipe) Andriis-MacBook-Air-2:ctasoft nagai$ python digicampipe/digicampipe/scripts/digicamview.py ~/Documents/work/data/CTA_data/09_04_2018/SST1M_01_ZFITSWRITER001_000.004.fits.fz 
Traceback (most recent call last):
  File "digicampipe/digicampipe/scripts/digicamview.py", line 7, in <module>
    from digicampipe.io import event_stream
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/event_stream.py", line 1, in <module>
    from digicampipe.io import zfits, hdf5
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/zfits.py", line 11, in <module>
    import digicampipe.io.protozfitsreader as protozfitsreader
  File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/protozfitsreader.py", line 6, in <module>
    import rawzfitsreader
ImportError: No module named 'rawzfitsreader'

**Comment by dneise** [comment]
Okay it looks you DYLD_LIBRARY_PATH is not correctly set:
It has these 3 parts:

    * /usr/local/Cellar/root/6.12.04_1/lib/root
    * /Users/nagai/Documents/work/Geant/geant4.10.3-install/lib
    * /Users/nagai/.local/lib/python3.5/site-packages

There should be something like this:

  * `/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/protozfitsreader`

So I suggest you put this line into your `/Users/nagai/.bashrc`:

    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HOME/anaconda2/envs/digicampipe/lib/python3.5/site-packages/protozfitsreader

----

NB: I think I just found another mistake in the README of the `protozfitsreader` ... :-(, there the last `protozfitsreader` in the LIBRARY_PATH was missing.

**Comment by dneise** [comment]
In order to test if this worked, you would have to close and reopen the terminal, in order to reload your `.bashrc`. Then again the lovely: `source activate digicampipe` and you are ready for:

```python
>>> import protozfitsreader
```

**Comment by AndriiNagai** [comment]
Thank you Dominik,
I updated my basic, now it has correct DYLD_LIBRARY_PATH:

    /usr/local/Cellar/root/6.12.04_1/lib/root:/Users/nagai/Documents/work/Geant/geant4.10.3-install/lib:/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/protozfitsreader   

and import protozfitsreader also works

    (digicampipe) Andriis-MacBook-Air-2:digicampipe nagai$ python
    Python 3.5.4 |Anaconda, Inc.| (default, Nov  8 2017, 18:11:28) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin Type "help", "copyright", "credits" or "license" for more information
    >>>
    >>> 
    >>> import protozfitsreader
    >>>

however, digicamview.py does not(((

    (digicampipe) Andriis-MacBook-Air-2:digicampipe nagai$ python digicampipe/scripts/digicamview.py ~/Documents/work/data/CTA_data/09_04_2018/SST1M_01_ZFITSWRITER001_000.004.fits.fz 
    Traceback (most recent call last):
    File "digicampipe/scripts/digicamview.py", line 7, in <module>
    from digicampipe.io import event_stream File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site packages/digicampipe/io/event_stream.py", line 1, in <module>
    from digicampipe.io import zfits, hdf5 File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/zfits.py", line 11, in <module>
    import digicampipe.io.protozfitsreader as protozfitsreader File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/protozfitsreader.py", line 6, in <module>
    import rawzfitsreader
    ImportError: No module named 'rawzfitsreader'.

**Comment by dneise** [comment]
Interesting ... I see one strange thing:

You seem to have installed `digicampipe` into your site packages
```
/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/protozfitsreader.py
```
but we usually install digicampipe in the so called "--editable" mode, in editable mode, nothing is copied to `site_packages` ... 

You install in "editable" mode by doing `pip install -e` as opposed to `pip install`. The advantage is that you can edit the files of digicampipe and play around with stuff, and you do not have to `pip install` the package again in order to use it.

So at some point in the past, you might have done `pip install digicampipe`... 

However this is not the real cause of the problem. The problem seems to be, that your version of digicampipe in your site_packages folder is still the old version.

I see that the old version seems to be used here because of this part of the traceback:
```
File "/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site-packages/digicampipe/io/zfits.py", line 11, in <module>
import digicampipe.io.protozfitsreader as protozfitsreader 
```

However this does not exist (anymore) in `zfits.py`.. the area around line 11 in `zfits.py` today looks like this:
https://github.com/cta-sst-1m/digicampipe/blob/eed73aba1167944b172d83b7d2733a981e0c3143/digicampipe/io/zfits.py#L9-L12

But when I go back in time to last october or so, we see this:
https://github.com/cta-sst-1m/digicampipe/blob/fee9f02809090623e516abcf8bbbd4fa076428a6/digicampipe/io/zfits.py#L9-L12

So you are somehow running mixed versions.

I am not sure how and when this happens.... 

I would recommend to think about wiping the complete conda environment (after all this is what environments are there for ... to be able to remove them and re-build them without negative effects on other python projects)

....

If you do not want to wipe your environment and reinstall from scratch I would try to simply: 

    pip uninstall digicampipe --yes

and hope pip somehow remembers that you have (an old) digicampipe in your site packages and removes it. If pip does not remove it, you can try to remove this folder manually:

    /Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site packages/digicampipe

If you now get something like 

    ImportError: No module named 'digicampipe'.

You might want to try to reinstall digicampipe from the fresh clone, i.e.

    cd into_the_place_where_you_cloned_digicampipe
    pip install -e digicampipe
    pytest digicampipe

**Comment by dneise** [comment]
Hello Andrii, are there any news about this?

**Comment by AndriiNagai** [comment]
Hi Dominik,
Sorry, I was busy with measurements and its analysis...
Just now I did your advices:

> pip uninstall digicampipe --yes
 removed manually:
/Users/nagai/anaconda2/envs/digicampipe/lib/python3.5/site packages/digicampipe
cd into_the_place_where_you_cloned_digicampipe
pip install -e digicampipe
pytest digicampipe

and it seems to work somehow. pytest digicampipe ended with:  **18 passed, 2 deselected, 10 xfailed in 24.88**

Thank You very much!

**Comment by dneise** [comment]
I am sorry this was such a pain to get installed ..
